# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/users.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pb/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epb/users.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"A\n\x0fGetUsersRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"C\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\" \n\x12GetUserByIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIDResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"@\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"@\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x12\x44\x65leteUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd3\x02\n\x05Users\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\x12\x44\n\x0bGetUserByID\x12\x19.users.GetUserByIDRequest\x1a\x1a.users.GetUserByIDResponse\x12\x41\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12\x41\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=59
  _globals['_USER']._serialized_end=220
  _globals['_GETUSERSREQUEST']._serialized_start=222
  _globals['_GETUSERSREQUEST']._serialized_end=287
  _globals['_GETUSERSRESPONSE']._serialized_start=289
  _globals['_GETUSERSRESPONSE']._serialized_end=356
  _globals['_GETUSERBYIDREQUEST']._serialized_start=358
  _globals['_GETUSERBYIDREQUEST']._serialized_end=390
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=392
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=440
  _globals['_CREATEUSERREQUEST']._serialized_start=442
  _globals['_CREATEUSERREQUEST']._serialized_end=488
  _globals['_CREATEUSERRESPONSE']._serialized_start=490
  _globals['_CREATEUSERRESPONSE']._serialized_end=554
  _globals['_UPDATEUSERREQUEST']._serialized_start=556
  _globals['_UPDATEUSERREQUEST']._serialized_end=602
  _globals['_UPDATEUSERRESPONSE']._serialized_start=604
  _globals['_UPDATEUSERRESPONSE']._serialized_end=668
  _globals['_DELETEUSERREQUEST']._serialized_start=670
  _globals['_DELETEUSERREQUEST']._serialized_end=701
  _globals['_DELETEUSERRESPONSE']._serialized_start=703
  _globals['_DELETEUSERRESPONSE']._serialized_end=752
  _globals['_USERS']._serialized_start=755
  _globals['_USERS']._serialized_end=1094
# @@protoc_insertion_point(module_scope)
